sudo: false
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
before_script:
  - if [ "$DB" = "mysql" ] ; then mysql -u root -e 'create database coda'; fi
  - if [ "$DB" = "mysql" ] ; then mysql -u root -e 'create user "coda" identified by "my_pass"'; fi
  - if [ "$DB" = "mysql" ] ; then mysql -u root -e 'grant all on *.* to coda'; fi
- pip install -e .
- pip install pep8
- pip install nose2
- pip install coverage
- pip install commonconf
- pip install python-coveralls
- cp travis-ci/manage.py manage.py
- python manage.py migrate
script:
- pep8 coursedashboards --exclude=migrations,static
- coverage run --source=coursedashboards/ --omit=coursedashboards/migrations/* manage.py test coursedashboards
after_script:
- coveralls
