version: '3.4'

services:
  app:
    environment:
      ENV: localdev
      PORT: 8000
      AUTH: SAML_MOCK
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    restart: always
    container_name: app-coda
    build:
      context: .
      target: app-container
    volumes:
      - ./coursedashboards:/app/coursedashboards
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
