version: '3.4'

services:
  app:
    environment:
      - ENV=localdev
      - PORT=8000
      - AUTH=SAML_MOCK
      - CODA_PROFILE=TRUE
    restart: always
    container_name: app-coda
    build:
      context: .
      target: app-container
    volumes:
      - ./coursedashboards:/app/coursedashboards
    ports:
      - "8000:8000"
