version: '3.4'

services:
  app:
    build:
      context: .
      target: app-container
    restart: always
    container_name: coursedashboards_app
    environment:
      - GOOGLE_ANALYTICS_KEY=${GOOGLE_ANALYTICS_KEY}
      - ENV=localdev
      - PORT=8000
      - AUTH=SAML_MOCK
      - CODA_PROFILE=TRUE
    volumes:
      - ./coursedashboards:/app/coursedashboards
      - statics-volume:/static
    ports:
      - "${RUNSERVER_PORT:-8000}:8000"
    stdin_open: true
    tty: true
  node-bundler:
    build:
      context: .
      target: node-bundler
    restart: always
    container_name: coursedashboards_node
    ports:
      - "${BUNDLE_ANALYZER_PORT:-8888}:8888" # Required when environment.BUNDLE_ANALYZER is true
    environment:
      VUE_DEVTOOLS: "True"
      BUNDLE_ANALYZER: "True"
    volumes:
      - ./coursedashboards:/app/coursedashboards # expose main django app so vite can output bundles here
      - ./coursedashboards_vue:/app/coursedashboards_vue
      - statics-volume:/static
    command: npm run watch
    stdin_open: true
    tty: true
volumes:
  statics-volume:
