version: '2'

services:
  app:
    environment:
      - ENV=localdev
      - PORT=8000
      - AUTH=SAML_MOCK
    restart: always
    container_name: app-coda
    build:
      context: .
    volumes:
      - ./coursedashboards:/app/coursedashboards
    ports:
      - "8000:8000"
