# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-07 22:49


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursedashboards', '0003_registration_is_repeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='is_repeat',
            field=models.NullBooleanField(),
        ),
    ]
