# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-18 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursedashboards', '0006_auto_20170918_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concurrentcourse',
            name='concurrent_course',
        ),
        migrations.RemoveField(
            model_name='concurrentcourse',
            name='course_offering',
        ),
        migrations.AlterUniqueTogether(
            name='courseofferingmajor',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='courseofferingmajor',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courseofferingmajor',
            name='major',
        ),
        migrations.RemoveField(
            model_name='courseofferingmajor',
            name='term',
        ),
        migrations.AddField(
            model_name='studentmajor',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='coursedashboards.Term'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_enrolled',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='coursedashboards.Term'),
        ),
        migrations.AlterField(
            model_name='term',
            name='quarter',
            field=models.CharField(choices=[(b'winter', b'Winter'), (b'spring', b'Spring'), (b'summer', b'Summer'), (b'autumn', b'Autumn')], max_length=6),
        ),
        migrations.AlterUniqueTogether(
            name='studentmajor',
            unique_together=set([('user', 'major', 'term')]),
        ),
        migrations.DeleteModel(
            name='ConcurrentCourse',
        ),
        migrations.DeleteModel(
            name='CourseOfferingMajor',
        ),
    ]
