# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-25 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursedashboards', '0010_auto_20171025_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffering',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
