# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-19 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursedashboards', '0010_auto_20171025_2100'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='registration',
            index_together=set([('term', 'course')]),
        ),
    ]
