# Copyright 2021 UW-IT, University of Washington
# SPDX-License-Identifier: Apache-2.0

# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-19 21:27


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursedashboards', '0010_auto_20171025_2100'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='registration',
            index_together=set([('term', 'course')]),
        ),
    ]
