# Generated by Django 2.1.15 on 2020-09-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursedashboards', '0013_auto_20190108_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGradeAverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum', models.CharField(max_length=20)),
                ('course_number', models.PositiveSmallIntegerField()),
                ('grade', models.CharField(max_length=5, null=True)),
            ],
            options={
                'db_table': 'CourseGradeAverage',
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='course_title',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='term',
            name='quarter',
            field=models.CharField(choices=[('winter', 'Winter'), ('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn')], max_length=6),
        ),
    ]
