# Copyright 2021 UW-IT, University of Washington
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 2.2.19 on 2021-03-17 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursedashboards', '0014_auto_20200911_2040'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='coursegradeaverage',
            index=models.Index(fields=['curriculum', 'course_number'], name='CourseGrade_curricu_18fdcc_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['grade', 'credits'], name='Registratio_grade_25d3ca_idx'),
        ),
    ]
