# Generated by Django 3.2.20 on 2023-09-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursedashboards', '0016_user_intro_modal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='major',
            field=models.CharField(max_length=128),
        ),
        migrations.AddIndex(
            model_name='major',
            index=models.Index(fields=['major'], name='major_name_idx'),
        ),
    ]
