# Generated by Django 5.2.13 on 2026-05-03 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursedashboards', '0017_auto_20230901_1003'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='registration',
            new_name='Registratio_term_id_0ecdcb_idx',
            old_fields=('term', 'course'),
        ),
    ]
