autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
targetAverageUtilization: 100
resources:
  limits:
    cpu: 512m
    memory: 1024Mi
  requests:
    cpu: 256m
    memory: 512Mi
ingress:
  enabled: true
  type: nginx
  tls:
    coda-prod:
      secretName: coda.uw.edu-ingress-cert
      hosts:
        - coda.uw.edu
  hosts:
    coda-prod:
      host: coda.uw.edu
      paths:
        - "/"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
lifecycle:
  enabled: true
  preStop:
    enabled: true
affinity:
   podsSpanNodes: true
readiness:
  enabled: true
database:
  engine: mysql
  name: coda
  hostname: coda-db-prod-service
  secretName: coda.uw.edu-sql-secrets
externalService:
  enabled: true
  name: coda-db-prod-service
  type: ClusterIP
  serviceAddress: 172.18.0.7
  servicePort: 3306
repo: coda
instance: prod
image:
  repository: registry.hub.docker.com/acait/coda
  tag: IMAGE_TAG
memcached:
  enabled: true
  replicaCount: 2
  updateStrategy:
    type: RollingUpdate
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
cronjob:
  enabled: true
  jobs:
    - name: load-term-data
      schedule: "15 4 * * *"
      command: ["/scripts/management_command.sh"]
      args: ["load_data_for_term"]
certs:
  mounted: true
  certPath: /certs/coda.uw.edu-uwca.cert
  keyPath: /certs/coda.uw.edu-uwca.key
  secretName: coda.uw.edu-uwca-certs
environmentVariables:
  - name: ENV
    value: dev
  - name: SESSION_BACKEND
    value: MEMCACHED
  - name: GWS_ENV
    value: PROD
  - name: SWS_ENV
    value: PROD
  - name: PWS_ENV
    value: PROD
  - name: CANVAS_ENV
    value: PROD
  - name: AUTH
    value: SAML
  - name: SAML_ENTITY_ID
    value: https://coda.uw.edu/shibboleth
  - name: CLUSTER_CNAME
    value: coda.uw.edu
  - name: MEMCACHED_MAX_POOL_SIZE
    value: "10"

externalSecrets:
  enabled: true
  secrets:
    - name: coda.uw.edu-secrets
      externalKey: axdd/kv/data/coda/prod/secrets
      data:
        - name: django-secret
          property: django-secret
    - name: coda.uw.edu-sql-secrets
      externalKey: axdd/kv/data/coda/prod/sql-secrets
      data:
        - name: username
          property: sql_user
        - name: password
          property: sql_pass
    - name: coda.uw.edu-uwca-certs
      externalKey: axdd/kv/data/coda/prod/uwca-certs
      data:
        - name: coda.uw.edu-uwca.key
          property: key
        - name: coda.uw.edu-uwca.cert
          property: cert
    - name: coda.uw.edu-ic-certs
      externalKey: axdd/kv/data/coda/prod/ic-certs
      data:
        - name: coda.uw.edu.cert
          property: cert
    - name: coda.uw.edu-uw-idp-cert
      externalKey: axdd/kv/data/idp-cert
      data:
        - name: uw-idp-cert
          property: cert

environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: coda.uw.edu-secrets
    secretKey: django-secret
  SAMLServiceProviderCert:
    name: SP_CERT
    secretName: coda.uw.edu-ic-certs
    secretKey: coda.uw.edu.cert
  SAMLIDPCert:
    name: IDP_CERT
    secretName: coda.uw.edu-uw-idp-cert
    secretKey: uw-idp-cert
