ingress:
  enabled: true
  type: nginx
  tls:
    coda-prod:
      secretName: coda.uw.edu-ingress-cert
      hosts:
        - coda.uw.edu
  hosts:
    coda-prod:
      host: coda.uw.edu
      paths: 
        - "/"
database:
  engine: mysql
  name: coda
  hostname: coda-db-prod-service
  secretName: coda-db-prod
externalService:
  enabled: true
  name: coda-db-prod-service
  type: ClusterIP
  serviceAddress: 172.18.0.7
  servicePort: 3306
repo: coda
instance: prod
targetAverageUtilization: 90
resources:
  limits:
    cpu: 600m
  requests:
    cpu: 200m
image:
  repository: registry.hub.docker.com/acait/coda
  tag: IMAGE_TAG
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
cronjob:
  enabled: true
  jobs:
    - name: load-term-data
      schedule: "15 4 * * *"
      command: '["bash"]'
      args: '["-c", "(cd /app && source ./bin/activate && ./bin/python manage.py load_data_for_term)"]'
certs:
  mounted: true
  certPath: /certs/coda.uw.edu-uwca.cert
  keyPath: /certs/coda.uw.edu-uwca.key
  secretName: coda-prod-uwca-certs
environmentVariables:
  - name: ENV
    value: dev
  - name: CERT_PATH
    value: /certs/coda.uw.edu-uwca.cert
  - name: KEY_PATH
    value: /certs/coda.uw.edu-uwca.key
  - name: GWS_ENV
    value: PROD
  - name: SWS_ENV
    value: PROD
  - name: PWS_ENV
    value: PROD
  - name: CANVAS_ENV
    value: PROD
  - name: AUTH
    value: SAML
  - name: SAML_ENTITY_ID
    value: https://coda.uw.edu/saml
  - name: CLUSTER_CNAME
    value: coda.uw.edu
  - name: SP_CERT
    value: '''MIIFdzCCBF+gAwIBAgIRAK1LnPXlkLHdlmVb8wOcLc0wDQYJKoZIhvcNAQELBQAwdjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAk1JMRIwEAYDVQQHEwlBbm4gQXJib3IxEjAQBgNVBAoTCUludGVybmV0MjERMA8GA1UECxMISW5Db21tb24xHzAdBgNVBAMTFkluQ29tbW9uIFJTQSBTZXJ2ZXIgQ0EwHhcNMTcxMDA1MDAwMDAwWhcNMjAxMDA0MjM1OTU5WjCBoDELMAkGA1UEBhMCVVMxDjAMBgNVBBETBTk4MTk1MQswCQYDVQQIEwJXQTEQMA4GA1UEBxMHU2VhdHRsZTEZMBcGA1UECRMQNDU0NSAxNXRoIEF2ZSBORTEhMB8GA1UEChMYVW5pdmVyc2l0eSBvZiBXYXNoaW5ndG9uMQ4wDAYDVQQLEwVVVy1JVDEUMBIGA1UEAxMLY29kYS51dy5lZHUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDg06VKq+Z7JvYXl7sFhqn+46RPJCrfJn3pV/6u89wtwEN8Hq5npQcb7FbfL+LkZ99rZ3J4uj/cPIMio6+3AiQQ7lofnZ4pGOGaxUHD+1iZHZLvBhQ/ocmAdmljp3QDEjZggdmSpCaarXHoxxgTy/+DPXs0skc+gyOHjnIswEq1K2U+Remz8AT681CvHNfa9cR2sa1pB9hzj/uCbpuTiZ9l+wuR7VDHKrP47OOras2G80zNsDs4wMY9RftGlql0ie351BpoFrjo9GjVQWrPKq3/SuxqxF4/QzCa8KMmCC/VxiKOb/LPYormCwwyaxhz1uHlfkIqcibbdFQJJ7/VkZlTAgMBAAGjggHTMIIBzzAfBgNVHSMEGDAWgBQeBaN3j2yW4luHS6a0hqxxAAznODAdBgNVHQ4EFgQUUdgx+3sTCKMJMAGkBYN4XgvPu5QwDgYDVR0PAQH/BAQDAgWgMAwGA1UdEwEB/wQCMAAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMGcGA1UdIARgMF4wUgYMKwYBBAGuIwEEAwEBMEIwQAYIKwYBBQUHAgEWNGh0dHBzOi8vd3d3LmluY29tbW9uLm9yZy9jZXJ0L3JlcG9zaXRvcnkvY3BzX3NzbC5wZGYwCAYGZ4EMAQICMEQGA1UdHwQ9MDswOaA3oDWGM2h0dHA6Ly9jcmwuaW5jb21tb24tcnNhLm9yZy9JbkNvbW1vblJTQVNlcnZlckNBLmNybDB1BggrBgEFBQcBAQRpMGcwPgYIKwYBBQUHMAKGMmh0dHA6Ly9jcnQudXNlcnRydXN0LmNvbS9JbkNvbW1vblJTQVNlcnZlckNBXzIuY3J0MCUGCCsGAQUFBzABhhlodHRwOi8vb2NzcC51c2VydHJ1c3QuY29tMCoGA1UdEQQjMCGCC2NvZGEudXcuZWR1ghJjb2RhLWFwcDEucy51dy5lZHUwDQYJKoZIhvcNAQELBQADggEBAEB1r7/JjxuvyEVmO6pQY6SRFxlPB4bSC9oFUCJ7itecF3+Z3gbn8K5w909xtl5A19PjYzEXbd//Y4l7OnMvBSp1CCcO0gsyQBqBxkiGE+NaBRQZdZywfHjZZ6QgjQ0j1xgCSKjpgNTJTtBzrNcG5MTxaMRGHiuNkM9phtqKxi8HrSuF5uWvK+AAUyY4yXz1lccLFP7rJ7vkNSJ1T7vl6vI1VBgvGD+6XesYJMcl9T6MtXuMwTJVVU4ytarx9QrtyddYNlW2NHAiQQTHbZM1Peys821hA3dkj/kjLkoDh51KR33u9AQoo0QRjQtUbrOYF8xiiG/o5Wjy8hEcfv/BUqM='''
  - name: IDP_CERT
    value: 'MIID/TCCAuWgAwIBAgIJAMoYJbDt9lKKMA0GCSqGSIb3DQEBBQUAMFwxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJXQTEhMB8GA1UEChMYVW5pdmVyc2l0eSBvZiBXYXNoaW5ndG9uMR0wGwYDVQQDExRpZHAudS53YXNoaW5ndG9uLmVkdTAeFw0xMTA0MjYxOTEwMzlaFw0yMTA0MjMxOTEwMzlaMFwxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJXQTEhMB8GA1UEChMYVW5pdmVyc2l0eSBvZiBXYXNoaW5ndG9uMR0wGwYDVQQDExRpZHAudS53YXNoaW5ndG9uLmVkdTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMH9G8m68L0Hf9bmf4/7c+ERxgDQrbq50NfSi2YTQWc1veUIPYbZy1agSNuc4dwn3RtC0uOQbdNTYUAiVTcYgaYceJVB7syWf9QyGIrglZPMu98c5hWb7vqwvs6d3s2Sm7tBib2v6xQDDiZ4KJxpdAvsoPQlmGdgpFfmAsiYrnYFXLTHgbgCc/YhV8lubTakUdI3bMYWfh9dkj+DVGUmt2gLtQUzbuH8EU44vnXgrQYSXNQkmRcyoE3rj4Rhhbu/p5D3P+nuOukLYFOLRaNeiiGyTu3P7gtc/dy/UjUrf+pH75UUU7Lb369dGEfZwvVtITXsdyp0pBfun4CP808H9N0CAwEAAaOBwTCBvjAdBgNVHQ4EFgQUP5smx3ZYKODMkDglkTbduvLcGYAwgY4GA1UdIwSBhjCBg4AUP5smx3ZYKODMkDglkTbduvLcGYChYKReMFwxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJXQTEhMB8GA1UEChMYVW5pdmVyc2l0eSBvZiBXYXNoaW5ndG9uMR0wGwYDVQQDExRpZHAudS53YXNoaW5ndG9uLmVkdYIJAMoYJbDt9lKKMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADggEBAEo7c2CNHEI+Fvz5DhwumU+WHXqwSOK47MxXwNJVpFQ9GPR2ZGDAq6hzLJLAVWcY4kB3ECDkRtysAWSFHm1roOU7xsU9f0C17QokoXfLNC0d7KoivPM6ctl8aRftU5moyFJkkJX3qSExXrl053uxTOQVPms4ypkYv1A/FBZWgSC8eNoYnBnv1Mhy4m8bfeEN7qT9rFoxh4cVjMH1Ykq7JWyFXLEB4ifzH4KHyplt5Ryv61eh6J1YPFa2RurVTyGpHJZeOLUIBvJu15GzcexuDDXe0kg7sHD6PbK0xzEF/QeXP/hXzMxR9kQXB/IR/b2k4ien+EM3eY/ueBcTZ95dgVM='
environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: coda-prod-django-secret
    secretKey: django-secret
  emailHostUser:
    name: EMAIL_HOST_USER
    secretName: email-post-credentials
    secretKey: username
  emailHostPassword:
    name: EMAIL_HOST_PASSWORD
    secretName: email-post-credentials
    secretKey: password
