ingress:
  enabled: true
  type: nginx
  tls:
    coda-prod:
      secretName: coda.uw.edu-ingress-cert
      hosts:
        - coda.uw.edu
  hosts:
    coda-prod:
      host: coda.uw.edu
      paths: 
        - "/"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
readiness:
  enabled: true
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
affinity:
   podsSpanNodes: true
database:
  engine: mysql
  name: coda
  hostname: coda-db-prod-service
  secretName: coda-db-prod
externalService:
  enabled: true
  name: coda-db-prod-service
  type: ClusterIP
  serviceAddress: 172.18.0.7
  servicePort: 3306
repo: coda
instance: prod
targetAverageUtilization: 100
resources:
  limits:
    cpu: 512m
    memory: 1024Mi
  requests:
    cpu: 256m
    memory: 512Mi
image:
  repository: registry.hub.docker.com/acait/coda
  tag: IMAGE_TAG
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
cronjob:
  enabled: true
  jobs:
    - name: load-term-data
      schedule: "15 4 * * *"
      command: [/scripts/management_command.sh load_data_for_term]
certs:
  mounted: true
  certPath: /certs/coda.uw.edu-uwca.cert
  keyPath: /certs/coda.uw.edu-uwca.key
  secretName: coda-prod-uwca-certs
environmentVariables:
  - name: ENV
    value: dev
  - name: GWS_ENV
    value: PROD
  - name: SWS_ENV
    value: PROD
  - name: PWS_ENV
    value: PROD
  - name: CANVAS_ENV
    value: PROD
  - name: AUTH
    value: SAML
  - name: SAML_ENTITY_ID
    value: https://coda.uw.edu/shibboleth
  - name: CLUSTER_CNAME
    value: coda.uw.edu
  - name: SP_CERT
    value: 'MIIG5DCCBcygAwIBAgIQUM7R6TTAzZ3ld4nbNwTcHTANBgkqhkiG9w0BAQsFADB2MQswCQYDVQQGEwJVUzELMAkGA1UECBMCTUkxEjAQBgNVBAcTCUFubiBBcmJvcjESMBAGA1UEChMJSW50ZXJuZXQyMREwDwYDVQQLEwhJbkNvbW1vbjEfMB0GA1UEAxMWSW5Db21tb24gUlNBIFNlcnZlciBDQTAeFw0xOTAyMjIwMDAwMDBaFw0yMTAyMjEyMzU5NTlaMIGgMQswCQYDVQQGEwJVUzEOMAwGA1UEERMFOTgxOTUxCzAJBgNVBAgTAldBMRAwDgYDVQQHEwdTZWF0dGxlMRkwFwYDVQQJExA0NTQ1IDE1dGggQXZlIE5FMSEwHwYDVQQKExhVbml2ZXJzaXR5IG9mIFdhc2hpbmd0b24xDjAMBgNVBAsTBVVXLUlUMRQwEgYDVQQDEwtjb2RhLnV3LmVkdTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMLhOaPAIqbswQv7gy+n/vQC+V+6aTtt1RFMf30HTBy10TKYz9QxjqGaar2auFa+Q6lgdREL5G7oZNVxid+iKg9HTR4pEdfgiaPGvWYItiF3dob0mIMJR/hMdD38tU4hdTPkRUSJ6tWtklk5bZB3i9RAd/3l986f33qWH5Weygo3P1wOXdZ70+kaSAkQeJuVtt0i3syl3F4Jkfiv2+fjt0OTt96DGJ6cTa8venJ4IzH6enO70v2AIwQSZuWd6Bx8Y4UxBYxklu1fa6D6t8k3Lb/1Qtn0zKecdqUCchXEijdjSKlm4D1EPBbi2DW8d683U0/A3hZeGjLk3YnKnBBu+48CAwEAAaOCA0EwggM9MB8GA1UdIwQYMBaAFB4Fo3ePbJbiW4dLprSGrHEADOc4MB0GA1UdDgQWBBQ+/FHxbMb9JuWQ5AAlIhXMXKaDwjAOBgNVHQ8BAf8EBAMCBaAwDAYDVR0TAQH/BAIwADAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwZwYDVR0gBGAwXjBSBgwrBgEEAa4jAQQDAQEwQjBABggrBgEFBQcCARY0aHR0cHM6Ly93d3cuaW5jb21tb24ub3JnL2NlcnQvcmVwb3NpdG9yeS9jcHNfc3NsLnBkZjAIBgZngQwBAgIwRAYDVR0fBD0wOzA5oDegNYYzaHR0cDovL2NybC5pbmNvbW1vbi1yc2Eub3JnL0luQ29tbW9uUlNBU2VydmVyQ0EuY3JsMHUGCCsGAQUFBwEBBGkwZzA+BggrBgEFBQcwAoYyaHR0cDovL2NydC51c2VydHJ1c3QuY29tL0luQ29tbW9uUlNBU2VydmVyQ0FfMi5jcnQwJQYIKwYBBQUHMAGGGWh0dHA6Ly9vY3NwLnVzZXJ0cnVzdC5jb20wFgYDVR0RBA8wDYILY29kYS51dy5lZHUwggF+BgorBgEEAdZ5AgQCBIIBbgSCAWoBaAB1ALvZ37wfinG1k5Qjl6qSe0c4V5UKq1LoGpCWZDaOHtGFAAABaRa/y4oAAAQDAEYwRAIgEZVm0cq2XuvVPbiVCgUNt2Dzfi0nNdj0PT26BpghFsUCIBuerJubFibrnyiC2SHCIVvv4bJ0xHeG1ISONRaj3PsZAHYARJRlLrDuzq/EQAfYqP4owNrmgr7YyzG1P9MzlrW2gagAAAFpFr/L1wAABAMARzBFAiBKUH3HhhCifdGerrz54LdZTu86wMegl/HEYWluhe2MiAIhAKhAm/UWjiawqdMxAK/yD+QPxRwTAUDvMEWbzL9AU/LuAHcAXNxDkv7mq0VEsV6a1FbmEDf71fpH3KFzlLJe5vbHDsoAAAFpFr/L0AAABAMASDBGAiEA7WgAYbMHuz/5lCRJU8NXuAtvyuMUHtR5llOCAeNkLUICIQCmDaSjHbBHzVNbOIV26oCI5faNO1uN4GT+0/bn2/sgMjANBgkqhkiG9w0BAQsFAAOCAQEAjnbSemxKAJJ5IHaYiOFv+1UBHdLOEKN8X7LNhtDUQ+9wCaD3ms/nmEaNdTRwYWZeF/m4cRt5WDI4lDFIO1NV0VGV9ML3wU/CrrKoDbi8nDRTAS9ql35T/BH39TL/5943iDuB1hPJibzvR5AOOn/rmjtVvuQhzIPML76wwT7+zdTHt8KUKKMEj/pxmIVBpabrksQ5s4aanMAf/Tgp4RG4UMKnQu6Muh0bvxe5oLnX721bz1HbS5aFTM5oiVeZTyyonehOr+V8/S+vfQW7LASbU/rfSFF06C9bc7Mg0XtZZnmh4mksf5Dgis2opdpN30vR09b1ZvhJXpa6bqUynbHzMQ=='
  - name: IDP_CERT
    value: 'MIID/TCCAuWgAwIBAgIJAMoYJbDt9lKKMA0GCSqGSIb3DQEBBQUAMFwxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJXQTEhMB8GA1UEChMYVW5pdmVyc2l0eSBvZiBXYXNoaW5ndG9uMR0wGwYDVQQDExRpZHAudS53YXNoaW5ndG9uLmVkdTAeFw0xMTA0MjYxOTEwMzlaFw0yMTA0MjMxOTEwMzlaMFwxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJXQTEhMB8GA1UEChMYVW5pdmVyc2l0eSBvZiBXYXNoaW5ndG9uMR0wGwYDVQQDExRpZHAudS53YXNoaW5ndG9uLmVkdTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMH9G8m68L0Hf9bmf4/7c+ERxgDQrbq50NfSi2YTQWc1veUIPYbZy1agSNuc4dwn3RtC0uOQbdNTYUAiVTcYgaYceJVB7syWf9QyGIrglZPMu98c5hWb7vqwvs6d3s2Sm7tBib2v6xQDDiZ4KJxpdAvsoPQlmGdgpFfmAsiYrnYFXLTHgbgCc/YhV8lubTakUdI3bMYWfh9dkj+DVGUmt2gLtQUzbuH8EU44vnXgrQYSXNQkmRcyoE3rj4Rhhbu/p5D3P+nuOukLYFOLRaNeiiGyTu3P7gtc/dy/UjUrf+pH75UUU7Lb369dGEfZwvVtITXsdyp0pBfun4CP808H9N0CAwEAAaOBwTCBvjAdBgNVHQ4EFgQUP5smx3ZYKODMkDglkTbduvLcGYAwgY4GA1UdIwSBhjCBg4AUP5smx3ZYKODMkDglkTbduvLcGYChYKReMFwxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJXQTEhMB8GA1UEChMYVW5pdmVyc2l0eSBvZiBXYXNoaW5ndG9uMR0wGwYDVQQDExRpZHAudS53YXNoaW5ndG9uLmVkdYIJAMoYJbDt9lKKMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADggEBAEo7c2CNHEI+Fvz5DhwumU+WHXqwSOK47MxXwNJVpFQ9GPR2ZGDAq6hzLJLAVWcY4kB3ECDkRtysAWSFHm1roOU7xsU9f0C17QokoXfLNC0d7KoivPM6ctl8aRftU5moyFJkkJX3qSExXrl053uxTOQVPms4ypkYv1A/FBZWgSC8eNoYnBnv1Mhy4m8bfeEN7qT9rFoxh4cVjMH1Ykq7JWyFXLEB4ifzH4KHyplt5Ryv61eh6J1YPFa2RurVTyGpHJZeOLUIBvJu15GzcexuDDXe0kg7sHD6PbK0xzEF/QeXP/hXzMxR9kQXB/IR/b2k4ien+EM3eY/ueBcTZ95dgVM='
environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: coda-prod-django-secret
    secretKey: django-secret
  emailHostUser:
    name: EMAIL_HOST_USER
    secretName: email-post-credentials
    secretKey: username
  emailHostPassword:
    name: EMAIL_HOST_PASSWORD
    secretName: email-post-credentials
    secretKey: password
